### ISSUE TITLE
Ошибка сразу после установки

### ISSUE THREAD

**Issue by vtec83** [skeeks-cms/app-shop-smarty#6]
Здравствуйте. Установил магазин, но запустить так и не получается.
Это я установил криво или реально класса не хватает?
Спасибо.

Error: Class 'NumberFormatter' not found in /var/www/sites/tkanivtomske.ru/vendor/skeeks/cms-module-money/src/IntlFormatter.php:39
Stack trace:
#0 /var/www/sites/tkanivtomske.ru/vendor/skeeks/cms-module-money/src/components/money/Money.php(134): skeeks\modules\cms\money\IntlFormatter->__construct('ru')
#1 /var/www/sites/tkanivtomske.ru/vendor/skeeks/cms-module-money/src/components/money/Money.php(157): skeeks\modules\cms\money\components\money\Money->intlFormatter('ru')
#2 /var/www/sites/tkanivtomske.ru/frontend/templates/default/widgets/ContentElementsCmsWidget/product-home-item.php(65): skeeks\modules\cms\money\components\money\Money->convertAndFormat(Object(skeeks\modules\cms\money\Money))
#3 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/View.php(332): require('/var/www/sites/...')
#4 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/sites/...', Array)
#5 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/var/www/sites/...', Array, NULL)
#6 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/widgets/ListView.php(191): yii\base\View->render('product-home-it...', Array)
#7 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/widgets/ListView.php(124): yii\widgets\ListView->renderItem(Object(skeeks\cms\shop\models\ShopCmsContentElement), 12760, 0)
#8 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/widgets/BaseListView.php(160): yii\widgets\ListView->renderItems()
#9 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/widgets/BaseListView.php(135): yii\widgets\BaseListView->renderSection('{items}')
#10 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array)
#11 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/widgets/BaseListView.php(138): preg_replace_callback('/{\\w+}/', Object(Closure), '\n{items}')
#12 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/Widget.php(140): yii\widgets\BaseListView->run()
#13 /var/www/sites/tkanivtomske.ru/frontend/templates/default/widgets/ContentElementsCmsWidget/products-home.php(38): yii\base\Widget::widget(Array)
#14 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/View.php(332): require('/var/www/sites/...')
#15 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/sites/...', Array)
#16 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/var/www/sites/...', Array, Object(skeeks\cms\cmsWidgets\contentElements\ContentElementsCmsWidget))
#17 /var/www/sites/tkanivtomske.ru/vendor/skeeks/cms/src/traits/TWidget.php(181): yii\base\View->render('@app/views/widg...', Array, Object(skeeks\cms\cmsWidgets\contentElements\ContentElementsCmsWidget))
#18 /var/www/sites/tkanivtomske.ru/vendor/skeeks/cms/src/base/WidgetRenderable.php(44): skeeks\cms\base\Widget->render('@app/views/widg...', Array)
#19 /var/www/sites/tkanivtomske.ru/vendor/skeeks/cms/src/cmsWidgets/contentElements/ContentElementsCmsWidget.php(197): skeeks\cms\base\WidgetRenderable->_run()
#20 /var/www/sites/tkanivtomske.ru/vendor/skeeks/cms/src/base/Widget.php(187): skeeks\cms\cmsWidgets\contentElements\ContentElementsCmsWidget->_run()
#21 /var/www/sites/tkanivtomske.ru/vendor/skeeks/cms/src/traits/TWidget.php(95): skeeks\cms\base\Widget->run()
#22 /var/www/sites/tkanivtomske.ru/frontend/templates/default/modules/cms/tree/home.php(53): skeeks\cms\base\Widget::widget(Array)
#23 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/View.php(332): require('/var/www/sites/...')
#24 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/sites/...', Array)
#25 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/var/www/sites/...', Array, Object(skeeks\cms\controllers\TreeController))
#26 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('@app/views/modu...', Array, Object(skeeks\cms\controllers\TreeController))
#27 /var/www/sites/tkanivtomske.ru/vendor/skeeks/cms/src/base/Controller.php(55): yii\base\Controller->render('@app/views/modu...', Array)
#28 /var/www/sites/tkanivtomske.ru/vendor/skeeks/cms/src/controllers/TreeController.php(107): skeeks\cms\base\Controller->render('home', Array)
#29 [internal function]: skeeks\cms\controllers\TreeController->actionView()
#30 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#31 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#32 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('view', Array)
#33 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('cms/tree/view', Array)
#34 /var/www/sites/tkanivtomske.ru/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#35 /var/www/sites/tkanivtomske.ru/vendor/skeeks/cms/app-web.php(29): yii\base\Application->run()
#36 /var/www/sites/tkanivtomske.ru/frontend/web/index.php(37): include('/var/www/sites/...')
#37 {main}

**Comment by skeeks-semenov** [comment]
Нужно поставить php расширение http://php.net/manual/ru/book.intl.php
